tailwind.config.ts
1. Add folders
2. modified tailwind.config.ts
=> Add folders

src/common/components/typography/Typography.stories.tsx, src/common/components/typography/Typography.tsx, src/common/components/typography/typographyData.ts
refactored typography component 
created typographyData for mapping in stories
refactored stories
=> refactored typography

src/common/components/card/Card.stories.ts, src/common/components/typography/Typography.stories.tsx, src/common/components/typography/Typography.tsx, src/common/components/typography/index.ts, src/common/components/typography/typographyData.ts, src/common/components/typography/typographyVariants.ts
fixed types for typographyTags
added index.ts and fixed imports
=> IN-22/Refactor typography

src/common/components/index.ts, src/common/components/textfield/TextField.stories.tsx, src/common/components/textfield/TextField.tsx, src/common/components/textfield/TextField.types.ts, src/common/components/textfield/helper.ts, src/common/components/textfield/index.ts
=> Task/IN-13/Create TextFiled component

src/common/components/index.ts, src/common/components/textarea/TextArea.stories.tsx, src/common/components/textarea/TextArea.tsx, src/common/components/textarea/TextArea.types.ts, src/common/components/textarea/helper.ts, src/common/components/textarea/index.ts, src/common/components/textfield/TextField.tsx
=> Task/IN-7/Create TextArea

src/common/components/radioGroup/RadioGroup.stories.tsx, src/common/components/radioGroup/RadioGroup.tsx
вынес стили из компонента в отдельный объект
=> IN-31/refactor: refactor tailwind styles in radio group component

src/common/components/menu/Menu.stories.ts, src/common/components/menu/Menu.tsx, src/common/components/menu/MenuItem.tsx, src/common/components/menu/index.ts, src/pages/index.tsx, src/pages/messenger/index.tsx, src/pages/profile/index.tsx, src/pages/publication/index.tsx
=> In 16/menu

src/common/components/sideBar/SideBar.stories.ts, src/common/components/sideBar/SideBar.tsx, src/common/components/sideBar/index.ts, src/common/components/sideBar/navLink/NavLink.tsx, src/pages/index.tsx
- **Реализовал компонент `SideBar`**
- **Реализовал компонент `NavLink` для ссылок и кнопок**
=> In 10/sideBar

src/common/components/datePicker/DataPicker.stories.ts, src/common/components/datePicker/DatePicker.tsx
- **Фикс: добавил возможность disabled**
- **Добавил стили для disabled**
=> In 11 fix/datePicker

package.json, pnpm-lock.yaml, src/common/components/modal/Modal.stories.tsx, src/common/components/modal/Modal.tsx
- **Добавил компонент `Dialog` из radix**
- **Добавил стили для `Dialog`**
- **Добавил пропс (`crossOff`), отключающий кнопку закрытия модалки**
=> IN-74: add Modal component

.storybook/preview.ts, package.json, pnpm-lock.yaml, src/common/components/index.ts, src/common/components/toast/Toast.stories.tsx, src/common/components/toast/ToastContainer.tsx, src/common/components/toast/helpers.ts, src/common/components/toast/index.ts, src/pages/_app.tsx
=> Task/IN-17/Create Alerts

src/common/components/radioGroup/RadioGroup.stories.tsx, src/common/components/radioGroup/RadioGroup.tsx
=> IN-86/refactor: refactor styles in RadioGroup.tsx

src/common/components/header/Header.tsx, src/common/components/layout/Layout.tsx, src/common/components/layout/index.ts, src/pages/_app.tsx, src/pages/index.tsx, src/styles/globals.css
Дополнительно добавил пару кнопок для тестов роутов
=> In 40/create layout

src/common/components/termsPolicyLayout/TermsPolicyLayout.tsx, src/common/components/termsPolicyLayout/index.ts, src/common/components/typography/Typography.tsx, src/pages/auth/privacy-policy/index.tsx, src/pages/auth/sign-up/index.tsx, src/pages/auth/terms-of-service/index.tsx
added terms of service and privacy policy pages
added links to the pages in sign up form
change tag 'a' to Link from next in typographyTags
=> IN-42 / Terms of Service and Privacy Policy

.husky/pre-commit, .husky/prepare-commit-msg, package.json, pnpm-lock.yaml
Добавлена библиотека для прекоммита (нейминг коммита)
=> [IN-177] init: add jira-prepare-commit package

src/features/auth/api/auth.api.ts, src/features/auth/api/instance.ts, src/features/auth/model/signUp/useRegistrationConfirmation.ts, src/features/auth/model/types.ts
=> IN-184 fix: correct email confirmation and signUp

src/common/layout/layout/Layout.tsx, src/features/auth/model/authStore.ts
=> IN-188 fix: fix some console bugs

src/common/HOC/withProtection.tsx, src/features/auth/api/auth.api.ts, src/features/auth/api/authApi.types.ts, src/features/auth/api/instance.ts, src/features/auth/model/authStore.ts
- **Баг с разлогиниванием побежден**&#128524;
=> In 187 / fix logging out when updating a token

src/features/profile/settings/generalInfo/api/profile.api.ts, src/features/profile/settings/generalInfo/api/profile.endpoints.ts, src/features/profile/settings/generalInfo/model/profileStore.ts, src/features/profile/settings/generalInfo/model/useAvatarUpload.ts, src/features/profile/settings/generalInfo/model/useFillGeneralInfo.ts, src/features/profile/settings/generalInfo/ui/AddPhoto.tsx, src/features/profile/settings/generalInfo/ui/FormCalendar.tsx, src/features/profile/settings/generalInfo/ui/GeneralInfo.tsx
=> IN-192 / Delete Avatar

.env, .env.example, .env.production, .gitignore, README.md, locales/en.ts, locales/ru.ts, src/common/components/reCaptcha/BaseReCAPTCHA.tsx, src/common/enviroments.ts, src/common/hooks/useTranslation.ts, src/features/auth/model/forgotPassword/forgotPasswordSchema.ts, src/features/auth/model/forgotPassword/recoveryPasswordSchema.ts, src/features/auth/model/forgotPassword/useForgotPassword.ts, src/features/auth/model/forgotPassword/useRecoveryPassword.ts, src/features/auth/model/signIn/singInSchema.ts, src/features/auth/model/signIn/useSignIn.ts, src/features/auth/model/signUp/singUpSchema.ts, src/features/auth/model/signUp/useSignUp.ts, src/features/auth/ui/SignInForm.tsx, src/features/auth/ui/forgotPassword/ForgotPasswordForm.tsx, src/features/auth/ui/forgotPassword/RecoveryPasswordForm.tsx, src/features/auth/ui/signUp/SignUpForm.tsx
refactor:
-  README file, 
-  refactor zod schemes in signIn, signUp, recovery password, forgot password forms
=> IN-181 / refactor zod errors and README file

package.json, pnpm-lock.yaml
=> IN-209 / update Next

src/common/components/index.ts, src/features/auth/model/forgotPassword/useForgotPassword.ts, src/features/auth/model/forgotPassword/useRecoveryPassword.ts, src/features/auth/model/signIn/useSignIn.ts, src/features/auth/model/signUp/useSignUp.ts, src/features/profile/settings/devices/api/profile.devices.api.ts, src/features/profile/settings/devices/index.ts, src/features/profile/settings/devices/model/index.ts, src/features/profile/settings/devices/model/profileSessionsStore.ts, src/features/profile/settings/devices/model/useDevices.ts, src/features/profile/settings/devices/ui/Device.stories.ts, src/features/profile/settings/devices/ui/Device.tsx, src/features/profile/settings/devices/ui/Devices.tsx, src/features/profile/settings/devices/ui/OtherSessions.tsx, src/features/profile/settings/devices/ui/index.ts
=> [IN-213] bug: device bug

locales/en.ts, locales/ru.ts, src/common/utils/setTranslation.ts, src/features/profile/settings/devices/model/profileSessionsStore.ts, src/pages/_app.tsx
- **Добавил возможность смены языка внутри сторов**
=> [IN-204] Internationalization for the stores

src/features/createPost/api/addPost.types.ts, src/features/createPost/model/addPostStore.ts
=> [IN-222] fix: one photo upload

src/features/profile/ui/PhotoProfilePostsGallery.tsx
Устранил утечку памяти на странице профиля - возникла вследствии многократного перерендеринга (когда мало постов).
=> [IN-236] fix_a_memory_leak

src/features/createPost/model/adding/useAddPhotoModal.ts
=> [IN-240] fix: add extra check

src/common/HOC/types.ts, src/common/HOC/withProtection.tsx, src/common/HOC/withServerSide.tsx, src/common/components/checkbox/Checkbox.stories.ts, src/common/components/checkbox/index.ts, src/common/components/header/mobilePopover/index.ts, src/common/components/textfield/TextField.stories.tsx, src/common/form/FormCheckbox.tsx, src/common/hooks/index.ts, src/features/publicPosts/ui/index.ts, src/pages/404/index.tsx, src/pages/home/index.tsx, src/pages/index.tsx, src/pages/profile/[[...id]].tsx, src/pages/profile/settings/index.tsx
=> In 243 / Hot fix dev

src/common/HOC/withProtection.tsx, src/common/HOC/withServerSide.tsx, src/common/components/header/Header.stories.tsx, src/common/components/header/Header.tsx, src/common/components/logOutModal/LogOutModal.stories.tsx, src/common/components/menu/Menu.stories.ts, src/common/components/menu/Menu.stories.tsx, src/common/components/menu/Menu.tsx, src/common/layout/Layout.tsx, src/features/newsFeed/ui/EmptyFeed.tsx, src/features/profile/ui/NoPosts.tsx, src/pages/404/index.tsx, src/pages/500/index.tsx, src/pages/messenger/index.tsx, src/pages/publication/index.tsx
Например, отступы auth и шапка
=> IN-251 / fix some different styles for correct mobile display

src/common/HOC/withProtection.tsx, src/common/HOC/withServerSide.tsx, src/common/components/scrollbar/ScrollArea.tsx, src/features/publicPosts/ui/PublicPosts.tsx, src/features/publicPosts/ui/RegisteredUsersCounter.tsx
=> IN-235 / Responsive layout for PublicPosts

src/pages/auth/terms-of-service/index.tsx
- **Пофикшен баг:** При попытке открыть страницу `[Terms of Service](http://localhost:3000/en/auth/terms-of-service)` мгновенной редиректит на signIn
=> [IN-247] fix: redirect to TermsOfService

src/common/api/utils/updateToken.ts
При протухании access token не корректно отрабатывало обновление данного токена
Поправил, результат на скринах
=> [IN-256] fix: fix update token func

package.json, pnpm-lock.yaml
=> IN-253 / upgrade next

src/common/components/header/Header.tsx, tailwind.config.ts
- **Добавлен новый брэкпоинт для экранов, меньше 360px**
- **Адаптированы кнопки в хэдере для незарегистрированного пользователя на экранах шириной от 320 до 360px**
=> IN-258/adaptive for header buttons

src/common/components/menu/Menu.tsx, src/common/components/scrollbar/ScrollArea.tsx, src/features/profile/ui/Profile.tsx, src/features/profile/ui/ProfileStatistics.tsx
- **Пофикшен баг со смещением скролла от старта**
- **Добавлен адаптив для Menu и ProfileStatistics на экранах шириной до 320 до 360px**
=> In 260/ fix: scroll offset from the start

src/features/auth/model/forgotPassword/recoveryPasswordSchema.ts, src/features/auth/model/signIn/singInSchema.ts, src/features/profile/settings/devices/model/sessionsDataSchema.ts, src/features/profile/settings/generalInfo/model/generalInfoSchema.ts, src/pages/github/index.tsx
- fix imports in schemas
- delete unnecessary property on GitHubPage
=> [HOTFIX-261] hotFix

src/features/createPost/ui/adding/AddImageModal.tsx
- поправлено двойное открывание окна при добавлении нового поста
=> IN-269 fix / fix 2 open for adding photo

src/features/posts/api/posts.api.ts
=> [IN-274] ref: add helper method

src/pages/profile/[...id]/index.tsx
- микро-оптимизация очередности запросов на сервере
=> [IN-287] IN-289 refactor: small request optimization

locales/translations/en/profile.ts, locales/translations/ru/profile.ts, src/common/components/radioGroup/RadioGroup.tsx, src/common/enums/enums.ts, src/features/profile/settings/getSettingsTabs.tsx, src/features/profile/settings/index.ts, src/features/profile/settings/subscription/api/index.ts, src/features/profile/settings/subscription/api/subscription.api.ts, src/features/profile/settings/subscription/api/subscription.endpoints.ts, src/features/profile/settings/subscription/index.ts, src/features/profile/settings/subscription/model/index.ts, src/features/profile/settings/subscription/model/subscriptionStore.ts, src/features/profile/settings/subscription/model/types.ts, src/features/profile/settings/subscription/model/useAccountOptions.ts, src/features/profile/settings/subscription/ui/Subscription.tsx, src/features/profile/settings/subscription/ui/components/PaymentRadioGroup.tsx, src/features/profile/settings/subscription/ui/components/PriceList.tsx, src/features/profile/settings/subscription/ui/components/index.ts, src/features/profile/settings/subscription/ui/index.ts, src/features/profile/ui/ProfileAboutMe.tsx
- **Добавил возможность выбора тарифа оплаты**
=> In 275 / Account Management

src/common/components/pagination/PageButton.tsx, src/common/components/pagination/Pagination.tsx, src/common/components/pagination/PaginationRangeButtons.tsx, src/common/components/pagination/index.ts
- Убраны ошибки консоли на странице My payments. 
- Подправлены импорты в компоненте
Проблема была в чуть недоделанном компоненте пагинации.
=> IN-291 fix: fix console errors

src/common/hooks/useScreenWidth.ts
=> [IN-294] hydration error

src/common/components/header/mobilePopover/MobilePopover.tsx, src/common/paths.ts, src/features/profile/ui/Profile.tsx
=> [IN-295] button transition on mobile device
